### ISSUE TITLE
improvement: 改进安装脚本使其运行时接受 网卡值 做为输入参数

### ISSUE THREAD

**Issue by vitan** [Dataman-Cloud/agent-installer#27]
譬如：
主机网卡为 ens01 , 则我可以通过命令

sudo -H OMEGA_ENV=prod bash -c "$(curl -Ls https://raw.githubusercontent.com/Dataman-Cloud/agent-installer/master/install-agent.sh)" -s 97f98e29ff624ca38c4b5ec62036ac60 **-nic ens01**

直接告诉脚本应该使用哪一个网卡。

**Comment by cmingxu** [comment]
https://github.com/Dataman-Cloud/agent-installer/commit/b83519e949324565461cc64386e92154b34aac94

@vitan 这样可好？
